# DINOv2 Model Configuration
_target_: scdino.models.lightning.dinov2.DINOv2

name: "dinov2"

# Model architecture parameters
architecture:
  backbone:
    type: vit
    vit:
      in_chans: 5
      img_size: 56
      patch_size: 4
      embed_dim: 128
      depth: 12
      num_heads: 8
      drop_path_rate: 0.1
      mlp_ratio: 4
      reg_tokens: 8
  # DINO head parameters
  dino_head:
    embed_dim: 128
    hidden_dim: 256
    bottleneck_dim: 32
    output_dim: 2048
    batch_norm: false
  # IBOT head parameters
  ibot_head:
    embed_dim: 128
    hidden_dim: 256
    bottleneck_dim: 32
    output_dim: 2048 # 16384 
    batch_norm: false
  # Model behavior
  ibot_separate_head: false
  

training:
  # Trainer parameters
  max_epochs: 40
  # Optimizer parameters
  optimizer:
    lr: 8e-04
  # Teacher temperature schedule (linear warmup over training STEPS)
  teacher_temp:
    warmup_steps: 6000
    start_value: 0.04
    end_value: 0.07
  # Weight decay schedule
  weight_decay:
    start_value: 0.001
    end_value: 0.01
  # Momentum schedule
  momentum:
    start_value: 0.992
    end_value: 1.0
  # Loss function parameters
  losses:
    dino:
      output_dim: 2048
      student_temp: 0.1
      center_momentum: 0.9
      center_mode: "mean"
      weight: 1.0
    ibot:
      output_dim: 2048
      student_temp: 0.1
      center_mode: "mean"
      center_momentum: 0.9
      weight: 1.0
    koleo:
      p: 2
      eps: 1e-8
      weight: 0.1
  # kNN evaluation parameters
  knn_eval:
    enable_knn_eval: true
    knn_k: 20
    knn_temperature: 0.07
    knn_max_train_batches: 1000
    knn_val_chunk_size: 1024
    knn_train_chunk_size: 50000