defaults:
  - datamodule: chronotype
  - model: dinov2 # pretrained/dinov3-vits16 #pretrained/dinov2-large #dinov3-vitb16
  - _self_

mode: "inference" # needed for the transformation
seed: 42
max_train_batches: 1000 # limit processed batches
max_val_batches: 1000 # limit processed batches
n_cells_per_class: 1000 # limit number of cells per class for inference
local_model_path:  /home/jonas/Documents/Projects/active/scDINO/outputs/train/dinov2_chronotype/2026-05-05/15-25-29/hf_model # set to local HuggingFace model dir for scdino models, e.g. "outputs/train/.../hf_model", or null
channel_adaptation_flavor: "DINO4CELL_CONCAT" # "mean", "pick_1", "pick_2", "pick_3", "DINO4CELL_CONCAT", "DINO4CELL_MEAN"; only used for pretrained models to adapt them to non 3 channel images

# Hardware configuration
datamodule:
  loader:
    accelerator: "gpu"
    devices: 1
    num_workers: 24
    prefetch_factor: 2
    pin_memory: true
    batch_size: 256
    shuffle: true
    drop_last: true

eval:
  k: 20
  T: 0.07
  query_batch_size: 1024
  train_chunk_size: 50000
  umap:
    n_components: 2
    n_neighbors: 15
    min_dist: 0.1
    metric: "euclidean"
  viz:
    cells_per_class: 1000
  confusion_matrix:
    enabled: true
    normalize: true # row-normalize (recall per class); false for raw counts
  hdbscan:
    enabled: true
    min_cluster_size: 50
    min_samples: 5
    metric: "euclidean"
    l2_normalize: true # for l2 normalised features euclidean distance is equivalent to cosine similarity
    cluster_selection_method: "leaf"
    plot_distance_matrix: true

# Hydra configuration
hydra:
  run:
    dir: outputs/inference/${model.name}_${datamodule.dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true