_target_: src.scdino.data.CHRONOTYPEDataModule

defaults:
  - transforms: ${model}

dataset: "chronotype"
model: ${model}
mode: "${mode}"

paths:
  train_dir: ${oc.env:DATA_DIR}/train
  val_dir: ${oc.env:DATA_DIR}/val
  test_dir: 
  predict_dir: ["${oc.env:DATA_DIR}/val"] # string or list of strings

loader:
  batch_size: 64
  shuffle: true
  drop_last: true
  num_workers: 24
  prefetch_factor: 2
  pin_memory: true
  num_channels: 5
  norm_type: "clip_max" # "robust" , "robust_2", "clip_max"
  norm_dict:
    # raw: 
    #   mean: [341.3947, 961.2514, 707.2337, 231.5772, 278.2134]
    #   std: [433.8531,  155.0544, 1155.2095,  192.4057,  290.8554]
    robust:
      mean: [ 0.1078, -0.0185,  0.1480,  0.1136,  0.0834]
      std: [0.3315, 0.2383, 0.2977, 0.2919, 0.2919] 
    robust_2:
      mean: [0.2304, 0.0154, 0.2709, 0.1795, 0.1383]
      std: [0.3072, 0.1071, 0.3314, 0.2674, 0.2507]
    clip_max:
      mean: [341.3994, 961.2516, 707.3349, 231.5798, 278.2124]
      std: [431.7079,  153.2045, 1150.2218,  191.5242,  289.6709]
  max_vals_clip: [2000, 1300, 6000, 1000, 2500]
  max_train_samples: null

