_target_: scdino.data.CHRONOTYPEDataModule

defaults:
  - transforms: ${model}

dataset: "chronotype"
model: ${model}
mode: "${mode}"

paths:
  train_dir: ${oc.env:DATA_DIR}/train_all_filtered
  val_dir: ${oc.env:DATA_DIR}/val_all_filtered
  test_dir: 
  predict_dir: ["${oc.env:DATA_DIR}/val_all_filtered"] # string or list of strings

loader:
  batch_size: 64
  shuffle: true
  drop_last: true
  num_workers: 24
  prefetch_factor: 2
  pin_memory: true
  num_channels: 5
  norm_type: "clip_max" # "robust" , "robust_2", "clip_max"
  norm_dict:
    robust:
      mean: [ 0.1078, -0.0185,  0.1480,  0.1136,  0.0834]
      std: [0.3315, 0.2383, 0.2977, 0.2919, 0.2919] 
    robust_2:
      mean: [0.2304, 0.0154, 0.2709, 0.1795, 0.1383]
      std: [0.3072, 0.1071, 0.3314, 0.2674, 0.2507]
    clip_max:
      mean: [358.5443, 941.6513, 825.9841, 255.2261, 308.7898]
      std: [499.9700,  151.3277, 1314.0288,  311.5910,  399.3656]
  max_vals_clip: [3713.48, 1297.59, 6904.38, 3412.43, 3133.96]  # defined as the max 99% percentile across celltypes and channels
  max_train_samples: null

