_target_: scdino.data.CHRONOTYPEDataModule

defaults:
  - transforms: ${model}

dataset: "chronotype_2CH"
model: ${model}
mode: "${mode}"

paths:
  train_dir: ${oc.env:DATA_DIR}/train_2CH
  val_dir: ${oc.env:DATA_DIR}/val_2CH
  test_dir: 
  predict_dir: ["${oc.env:DATA_DIR}/val_2CH"] # string or list of strings

loader:
  batch_size: 64
  shuffle: true
  drop_last: true
  num_workers: 24
  prefetch_factor: 2
  pin_memory: true
  num_channels: 2
  norm_type: "robust_2" # "robust" , "robust_2", "clip_max"
  norm_dict:
    robust:
      mean: [-0.0185,  0.1480]
      std: [0.2383, 0.2977] 
    robust_2:
      mean: [0.0154, 0.2709]
      std: [0.1071, 0.3314]
    clip_max:
      mean: [961.2516, 707.3349]
      std: [153.2045, 1150.2218]
  max_vals_clip: [1300, 6000]
  max_train_samples: null

